version: '3.7'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    expose:
      - "9092"
      - "2181"
  test-kafka-console:
    container_name: test-kafka-console
    build: .